# Generated by Django 5.1.1 on 2024-09-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_moodentry_alter_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductEntry',
        ),
    ]
